/**
 * Browser summary formatter (app/assets/js/summary.js) against the shared vectors and the SUM
 * acceptance behaviors, using the render model served by the running application. The CFML twin
 * (WalkSummaryFormatterTest) runs the same vectors, so the two formatters are proven byte-identical
 * and the browser can never show a summary the server would export differently.
 *
 * tests/fixtures/summary-vectors.json is regenerated by scripts/generate-summary-vectors.mjs and
 * reviewed against source/current-prototype.html by scripts/prototype-summary-oracle.mjs.
 */
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { evaluate, normalize } from "../../app/assets/js/rules.js";
import {
  averageText,
  componentAverage,
  emailDraft,
  emailItem,
  exportSections,
  fileName,
  fileNameSpec,
  resolvePartSection,
  sanitizeFileLabel,
  selectableParts,
  summaryText,
  SUMMARY_CONTRACT,
} from "../../app/assets/js/summary.js";
import { baseUrl, loadRuntimeEnv, root } from "./helpers.mjs";

const env = loadRuntimeEnv();
const token = env.ICFWALK_MAINTENANCE_TOKEN || "";
const tag = `nodesum-${Date.now().toString(36)}`;
const subject = `${tag}-walker`;
const vectors = JSON.parse(fs.readFileSync(path.join(root, "tests", "fixtures", "summary-vectors.json"), "utf8"));

async function reachable() {
  try {
    const r = await fetch(`${baseUrl(env)}/index.cfm/api/health`, { signal: AbortSignal.timeout(10000) });
    if (r.status !== 200) return false;
    const body = await r.json();
    return body.environment === "development" || body.environment === "test";
  } catch {
    return false;
  }
}
const up = await reachable();
const skip = !up ? `application not reachable in development mode at ${baseUrl(env)}` : !token ? "no maintenance token" : false;

let model = null;

before(async () => {
  if (skip) return;
  const call = (p, body) =>
    fetch(`${baseUrl(env)}/index.cfm${p}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-ICFWalk-Maintenance-Token": token },
      body: JSON.stringify(body),
    });
  await call("/api/maintenance/org-units/import", {
    orgUnits: [{ code: `${tag}-district`, type: "DISTRICT", name: "Node summary district", parentCode: null }],
  });
  await call("/api/maintenance/identity/provision-user", { subject, displayName: "Node summary fixture" });
  await call("/api/maintenance/identity/assign-role", {
    subject,
    roleCode: "DISTRICT_WALK_REPORT",
    orgUnitCode: `${tag}-district`,
    includeDescendants: true,
  });
  const r = await fetch(`${baseUrl(env)}/index.cfm/api/instrument/current`, {
    headers: { "X-ICFWalk-Dev-Subject": subject, Accept: "application/json" },
  });
  const text = await r.text();
  assert.equal(r.status, 200, text);
  model = JSON.parse(text).model;
});

after(async () => {
  if (skip) return;
  const r = await fetch(`${baseUrl(env)}/index.cfm/api/maintenance/identity/cleanup-fixtures`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-ICFWalk-Maintenance-Token": token },
    body: JSON.stringify({ tag }),
  });
  if (r.status !== 200) console.error("fixture cleanup failed", r.status, await r.text());
});

const st = (dimensions = {}, responses = {}) => ({ dimensions, responses });
const evalOf = (state) => evaluate(model, state);
const sectionByKey = (key) => {
  const find = (node) => {
    if (node.sectionKey === key) return node;
    for (const child of node.children) {
      const hit = find(child);
      if (hit) return hit;
    }
    return null;
  };
  const hit = find(model.root);
  assert.ok(hit, `the instrument has no section '${key}'`);
  return hit;
};

test("JS formatter reproduces every shared vector (parity contract with the CFML formatter)", { skip }, () => {
  assert.equal(vectors.format, "icfwalk-summary-vectors/1");
  assert.equal(vectors.contract, SUMMARY_CONTRACT);
  assert.ok(vectors.vectors.length >= 10, "the shared vectors must cover every SUM case");
  for (const v of vectors.vectors) {
    const ev = evalOf(v.state);
    assert.equal(summaryText(model, v.state, ev), v.expected.summaryText, `${v.name}: summaryText`);
    assert.equal(fileName(model, v.state, ev, v.walkId), v.expected.fileName, `${v.name}: fileName`);
    for (const [keys, expected] of Object.entries(v.expected.emails)) {
      const draft = emailDraft(model, v.state, ev, keys ? keys.split(",") : []);
      assert.equal(draft.subject, expected.subject, `${v.name}: email[${keys}].subject`);
      assert.equal(draft.body, expected.body, `${v.name}: email[${keys}].body`);
    }
  }
});

test("the stored states are already normalized, so a vector describes a real persisted walk", { skip }, () => {
  for (const v of vectors.vectors) {
    const again = normalize(model, v.state, vectors.policies);
    assert.deepEqual(again.changes, [], `${v.name}: re-normalizing a stored state must change nothing`);
  }
});

test("averageText matches JavaScript toFixed(1) on every shared rounding vector", { skip }, () => {
  for (const c of vectors.averages) {
    assert.equal(averageText(c.sum, c.count), c.expected, `averageText(${c.sum}, ${c.count})`);
    if (c.count) assert.equal(c.expected, (c.sum / c.count).toFixed(1), `toFixed parity for ${c.sum}/${c.count}`);
  }
  // The cases the brief singles out: 2.25 is an exact binary tie, 3.05 is stored just below one.
  assert.equal(averageText(9, 4), "2.3");
  assert.equal(averageText(5, 2), "2.5");
  assert.equal(averageText(61, 20), "3.0");
  assert.equal(averageText(89, 20), "4.5");
  assert.equal(averageText(0, 0), "n/a");
});

test("SUM-02/COND-15 component averages use answered scores only; a blank is never a zero", { skip }, () => {
  const section = sectionByKey("s1");
  const both = st({}, { comp_s1_q1: { storedCode: "4" }, comp_s1_q2: { storedCode: "2" } });
  assert.equal(componentAverage(section, both, evalOf(both)), "3.0");
  const one = st({}, { comp_s1_q1: { storedCode: "4" } });
  assert.equal(componentAverage(section, one, evalOf(one)), "4.0", "a blank rating is excluded, not averaged as zero");
  const none = st();
  assert.equal(componentAverage(section, none, evalOf(none)), "n/a");
  // A code that is not an option of the set is not an answer and contributes no score.
  const foreign = st({}, { comp_s1_q1: { storedCode: "9" }, comp_s1_q2: { storedCode: "3" } });
  assert.equal(componentAverage(section, foreign, evalOf(foreign)), "3.0");
  // The export says so rather than printing a misleading 0.0.
  const text = summaryText(model, none, evalOf(none));
  assert.match(text, /2\.1 DAILY ENGAGEMENT WITH COMPLEX TEXTS {2}\(avg: n\/a\)/);
  assert.doesNotMatch(text, /\(avg: 0\.0\)/);
  assert.match(text, /\[not answered\]/);
});

test("SUM-03 a skipped component is labelled, has no average and no ratings, and keeps its notes", { skip }, () => {
  const state = st({}, { comp_s3_applicable: { storedCode: "no" }, comp_s3_notes: { textValue: "kept for follow-up" } });
  const text = summaryText(model, state, evalOf(state));
  assert.match(text, /2\.3 WORKSHOP MODEL OF INSTRUCTION {2}\(not part of this lesson at the time of the visit\)\nNotes: kept for follow-up/);
  assert.doesNotMatch(text, /2\.3 WORKSHOP MODEL OF INSTRUCTION {2}\(avg:/);
});

test("SUM-04 hidden sections and a hidden Period are excluded but not destroyed", { skip }, () => {
  const state = st(
    { grade: { selectedValueCode: "3" }, period: { selectedValueCode: "fourth" }, classType: { selectedValueCode: "general_education" } },
    { dual_language_q1: { storedCode: "yes" }, dual_language_notes: { textValue: "bridge time" } },
  );
  const ev = evalOf(state);
  assert.equal(ev.dimensionStates.period, "HIDDEN");
  assert.equal(ev.responseStates.dual_language_q1, "HIDDEN");
  const text = summaryText(model, state, ev);
  assert.doesNotMatch(text, /Period:/);
  assert.doesNotMatch(text, /Fourth/);
  assert.doesNotMatch(text, /DUAL LANGUAGE/);
  assert.doesNotMatch(text, /bridge time/);
  assert.match(text, /Grade level: 3/);
  // The values are still in the state; only the export excludes them.
  assert.equal(state.responses.dual_language_notes.textValue, "bridge time");

  const shown = st(
    { grade: { selectedValueCode: "7" }, period: { selectedValueCode: "fourth" }, classType: { selectedValueCode: "dual_language" } },
    { dual_language_q1: { storedCode: "yes" }, dual_language_notes: { textValue: "bridge time" } },
  );
  const shownText = summaryText(model, shown, evalOf(shown));
  assert.match(shownText, /Period: Fourth/);
  assert.match(shownText, /DUAL LANGUAGE CLASSROOM/);
  assert.match(shownText, /Notes: bridge time/);
});

test("SUM-05 file names carry only safe characters and no path can be steered through them", { skip }, () => {
  for (const c of vectors.fileLabels) assert.equal(sanitizeFileLabel(c.label), c.expected, `sanitizeFileLabel(${c.label})`);

  const punctuated = st({
    school: { selectedValueCode: "other", otherText: "Unlisted/Site?" },
    grade: { selectedValueCode: "9" },
    content: { selectedValueCode: "other", otherText: "Art & Design" },
    date: { dateValue: "2026-09-17" },
  });
  assert.equal(fileName(model, punctuated, evalOf(punctuated), "W1"), "ICFWalk_9_Art_Design_2026-09-17.txt");

  for (const attempt of ["../../etc/passwd", "..\\..\\windows\\system32", 'x"; rm -rf /', "a/b/c"]) {
    const state = st({ grade: { selectedValueCode: "9" }, content: { selectedValueCode: "other", otherText: attempt } });
    const name = fileName(model, state, evalOf(state), "W1");
    assert.match(name, /^ICFWalk_[A-Za-z0-9_-]+\.txt$/, `${attempt} -> ${name}`);
    for (const forbidden of ["..", "/", "\\", '"', ";", " "]) {
      assert.ok(!name.includes(forbidden), `${name} must not contain ${JSON.stringify(forbidden)}`);
    }
  }

  // Nothing named falls back to the walk id; a hidden dimension can never name the file.
  assert.equal(fileName(model, st(), evalOf(st()), "ABC-123"), "ICFWalk_ABC-123.txt");
  const hiddenPeriod = st({ grade: { selectedValueCode: "3" }, period: { selectedValueCode: "fourth" } });
  assert.equal(fileName(model, hiddenPeriod, evalOf(hiddenPeriod), "W1"), "ICFWalk_3.txt");
});

test("the file name is driven by behavior.export.fileNamePattern, not by a restated list", { skip }, () => {
  const spec = fileNameSpec(model);
  assert.deepEqual(spec, { prefix: "ICFWalk_", suffix: ".txt", separator: "_", dimensionCodes: ["grade", "content", "date"] });
  assert.equal(model.behavior.export.fileNamePattern, "ICFWalk_<grade>_<content>_<date>.txt");
  assert.throws(() => fileNameSpec({ behavior: { export: { fileNamePattern: "no-tokens.txt" } } }), /names no dimension/);
  assert.throws(() => fileNameSpec({ behavior: { export: { fileNamePattern: "<a>_<b>-<c>.txt" } } }), /mixes separators/);

  // The label is sanitized, but the pattern's literals are configuration. A pattern that could put
  // a quote, a path separator, or a traversal sequence into a Content-Disposition header is refused
  // rather than emitted, however the walk was filled in.
  const patterned = (pattern) => ({ ...model, behavior: { ...model.behavior, export: { ...model.behavior.export, fileNamePattern: pattern } } });
  const state = st({ grade: { selectedValueCode: "9" } });
  for (const bad of ['ICF"Walk_<grade>.txt', "../<grade>.txt", "dir/<grade>.txt", "ICFWalk_<grade>.t;xt", "..<grade>.txt"]) {
    assert.throws(() => fileName(patterned(bad), state, evalOf(state), "W1"), /unsafe file name/, bad);
  }
  // The real pattern is of course fine, and so is any pattern made only of safe characters.
  assert.equal(fileName(patterned("ICFWalk_<grade>.txt"), state, evalOf(state), "W1"), "ICFWalk_9.txt");
  assert.equal(fileName(patterned("walk-<grade>.text"), state, evalOf(state), "W1"), "walk-9.text");
});

test("SUM-06 the draft follows the settings order, includes only checked parts, and names its kinds", { skip }, () => {
  const state = st(
    {
      grade: { selectedValueCode: "9" },
      content: { selectedValueCode: "ela" },
      observer: { textValue: "Jane Doe" },
      date: { dateValue: "2026-09-17" },
    },
    {
      part1_adopted_notes: { textValue: "adopted note" },
      comp_s1_notes: { textValue: "s1 note" },
      comp_s3_applicable: { storedCode: "no" },
      conditions_notes: { textValue: "b note" },
      summary_strengths: { textValue: "strength" },
    },
  );
  const ev = evalOf(state);
  const keys = ["part1", "comp_s1", "belonging", "summary"];
  const inOrder = emailDraft(model, state, ev, keys);
  const shuffled = emailDraft(model, state, ev, [...keys].reverse());
  assert.equal(shuffled.subject, inOrder.subject, "the tick order must not change the subject");
  assert.equal(shuffled.body, inOrder.body, "the tick order must not change the body");

  assert.match(inOrder.body, /Part 1 — Target \/ Taxonomy \/ Pacing:\nAdopted Curriculum notes: adopted note/);
  assert.match(inOrder.body, /2\.1 — Daily Engagement with Complex Texts:\nNotes: s1 note/);
  assert.match(inOrder.body, /Part 3 — Conditions for Learning:\nNotes: b note/);
  assert.match(inOrder.body, /Part 4: Walk Summary:\nStrengths: strength/);
  assert.match(inOrder.body, /Jane Doe$/, "the observer signs the draft");
  assert.ok(!inOrder.body.includes("2.3 "), "an unchecked part must not appear");
  assert.ok(!inOrder.body.includes("Growth areas:"), "an empty Part 4 field must not appear in the email");
  assert.match(inOrder.subject, /^Quick note from today’s walk-through — 9 ELA \(/);

  // A component that is not part of the lesson says so, with no "no notes" line after it.
  const skipped = emailDraft(model, state, ev, ["comp_s3"]);
  assert.match(skipped.body, /2\.3 — Workshop Model of Instruction:\n• Not part of this lesson at the time of the visit\./);
  assert.ok(!skipped.body.includes("(No notes recorded for this component.)"));

  // Nothing checked: a prompt to check something, and no part list in the subject.
  const none = emailDraft(model, state, ev, []);
  assert.match(none.body, /\(No sections were selected — check at least one part above, then update the draft\.\)/);
  assert.ok(!none.subject.includes("("), "an empty selection adds no part list to the subject");

  // No observer: the placeholder a person replaces, never a blank signature.
  const noObserver = st({ ...state.dimensions }, state.responses);
  delete noObserver.dimensions.observer;
  assert.match(emailDraft(model, noObserver, evalOf(noObserver), ["summary"]).body, /\[Your name\]$/);

  // Empty parts say so rather than printing a bare heading.
  const empty = st({}, { comp_s3_applicable: { storedCode: "no" } });
  const emptyDraft = emailDraft(model, empty, evalOf(empty), ["part1", "belonging", "summary"]);
  assert.match(emptyDraft.body, /\(No notes recorded for this part\.\)/);
  assert.match(emptyDraft.body, /\(No summary notes recorded yet\.\)/);
});

test("every selectable part the instrument offers resolves to a section, and a bad one throws", { skip }, () => {
  const parts = selectableParts(model);
  assert.ok(parts.length >= 10, "the composer offers Part 1, the components, Part 3 and Part 4");
  for (const part of parts) {
    const section = resolvePartSection(model, part);
    assert.ok(section && section.sectionKey, `${part.key} resolves`);
  }
  assert.equal(emailItem(model).layout, "email-draft");
  assert.throws(() => resolvePartSection(model, { key: "ghost", kind: "component", partNum: "9.9", compId: "nope" }), /does not resolve/);
  // A key that names no selectable part simply selects nothing: the composer only ever writes keys
  // the item's settings declare, and a stored draft from an older version must not break the editor.
  const ghost = emailDraft(model, st(), evalOf(st()), ["not-a-part"]);
  assert.equal(ghost.subject, emailDraft(model, st(), evalOf(st()), []).subject);
  assert.match(ghost.body, /\(No sections were selected/);
});

test("brief 14.1 conditional cards print in prototype order: the content card before the class-type card", { skip }, () => {
  const order = exportSections(model).map((s) => s.sectionKey);
  assert.deepEqual(order.slice(0, 9), [
    "visit_information",
    "prek_k_classroom",
    "dual_language_classroom",
    "mac_prep_classroom",
    "ignite_classroom",
    "avid_classroom",
    "content_area_look_fors",
    "esl_classroom",
    "part1",
  ]);
  const state = st(
    { content: { selectedValueCode: "music" }, classType: { selectedValueCode: "esl" }, grade: { selectedValueCode: "10" } },
    { content_area_q1: { storedCode: "yes" }, esl_q1: { storedCode: "yes" } },
  );
  const text = summaryText(model, state, evalOf(state));
  assert.ok(text.indexOf("CONTENT-AREA LOOK-FORS") < text.indexOf("ESL CLASSROOM"));
});

test("SEC-02 stored markup is exported verbatim as text, never escaped and never dropped", { skip }, () => {
  const payload = 'Line 1 <b>bold</b> & "quotes" <script>alert(1)</script>';
  const state = st({ observer: { textValue: payload } }, { conditions_notes: { textValue: payload } });
  const text = summaryText(model, state, evalOf(state));
  assert.ok(text.includes(`Observer(s): ${payload}`));
  assert.ok(text.includes(`Notes: ${payload}`));
  assert.ok(!text.includes("&amp;"), "the export is text/plain: nothing is HTML-escaped into it");
  assert.ok(!text.includes("&lt;"), "the export is text/plain: nothing is HTML-escaped into it");
});

test("the text shape is stable: LF only, no trailing newline, no BOM", { skip }, () => {
  const text = summaryText(model, st(), evalOf(st()));
  assert.equal(text.slice(0, 32), "ICFWALK SUMMARY\n================");
  assert.ok(!text.endsWith("\n"), "there is no trailing newline");
  assert.ok(!text.includes("\r"), "there is no carriage return");
  assert.ok(!text.startsWith("﻿"), "there is no byte-order mark");
});

/**
 * SUM-07 depends on this: the browser must serialize the draft in exactly the key order
 * WalkPayloadValidator.validateEmailDraft canonicalizes to, or every reload would compare unequal
 * and the Phase 4 conflict panel would report a phantom unsent edit on a walk nobody touched.
 */
test("the composer's document serializes to the server's canonical form and survives a round trip", { skip }, async () => {
  const { readEmailDocument, serializeEmailDocument } = await import("../../app/assets/js/email-composer.js");
  const doc = { includedPartKeys: ["part1", "comp_s3"], drafted: true, to: "teacher@u46.org", subject: "S", body: "B" };
  const text = serializeEmailDocument(doc);
  assert.equal(text, '{"body":"B","drafted":true,"includedPartKeys":["part1","comp_s3"],"subject":"S","to":"teacher@u46.org"}');
  // Sorted keys, no whitespace: the same rules src/core/CanonicalJson.cfc follows.
  assert.deepEqual(Object.keys(JSON.parse(text)), ["body", "drafted", "includedPartKeys", "subject", "to"]);
  assert.deepEqual(readEmailDocument({ responses: { email_workflow: { textValue: text } } }, "email_workflow"), doc);
  assert.equal(serializeEmailDocument(readEmailDocument({ responses: { email_workflow: { textValue: text } } }, "email_workflow")), text);

  // Non-ASCII is emitted unescaped by both sides, so a curly apostrophe round-trips byte for byte.
  const unicode = serializeEmailDocument({ ...doc, body: "It\u2019s \u2014 fine" });
  assert.ok(unicode.includes("It\u2019s \u2014 fine"), unicode);

  // An absent, empty, malformed, or wrongly typed document must never break the editor.
  const empty = { includedPartKeys: [], drafted: false, to: "", subject: "", body: "" };
  for (const stored of [undefined, "", "not json", "[1,2]", "null", '{"drafted":"yes"}', '{"includedPartKeys":[1,2]}']) {
    const state = { responses: stored === undefined ? {} : { email_workflow: { textValue: stored } } };
    const parsed = readEmailDocument(state, "email_workflow");
    assert.equal(typeof parsed.to, "string", stored);
    assert.equal(typeof parsed.drafted, "boolean", stored);
    assert.ok(Array.isArray(parsed.includedPartKeys), stored);
    for (const key of parsed.includedPartKeys) assert.equal(typeof key, "string", stored);
  }
  assert.deepEqual(readEmailDocument({ responses: {} }, "email_workflow"), empty);
  assert.deepEqual(readEmailDocument({ responses: { email_workflow: { textValue: '{"drafted":"yes"}' } } }, "email_workflow"), empty,
    "a non-boolean flag is not treated as drafted by the browser");
});

test("the formatter is pure: it never mutates the state or the model it is given", { skip }, () => {
  const state = st(
    { grade: { selectedValueCode: "9" }, content: { selectedValueCode: "ela" } },
    { comp_s1_q1: { storedCode: "4" }, comp_s3_applicable: { storedCode: "no" } },
  );
  const before = JSON.stringify(state);
  const modelBefore = JSON.stringify(model);
  const ev = evalOf(state);
  summaryText(model, state, ev);
  fileName(model, state, ev, "W1");
  emailDraft(model, state, ev, ["part1", "summary"]);
  assert.equal(JSON.stringify(state), before, "the working state is untouched");
  assert.equal(JSON.stringify(model), modelBefore, "the render model is untouched");
});
